version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: djangodb
      MYSQL_USER: root
    volumes:
      - ./db:/var/lib/mysql